### PR TITLE
Tuple Edge case fixed

### PR DESCRIPTION
**Pull request by maxsam4**
Fixes https://github.com/federicobond/solidity-parser-antlr/issues/43

It's a very cheeky fix but it works :P.

We might wanna do a proper fix in future but this should work for now.

### CODE REVIEW

**Comment by federicobond** [comment]
@maxsam4 thank you for your contribution. As stated earlier, I'm not really sure this is the right approach since tuples of the form `(a,)` are considered as one dimensional.

Of course, one could make the case that in the left-hand side of an assignment `(a,)` is not a tuple but actually a series of l-values. I am not convinced enough to make a decision one way or another without more examples of library users bumping into this.

In the future, please include unit tests with your changes to compare the AST output.

**Comment by maxsam4** [comment]
@federicobond Thank you for your response. As I mentioned in the OP, this is "a very cheeky" fix. I wanted to get your opinion before spending time on the test cases. I added the test contract to demo the issue.

I'll push the AST test case for this.

ps. I am using native solc 0.5.2

**Comment by maxsam4** [comment]
I have pushed the AST test case.
Also, I have removed the test contract that I added earlier because the same case is covered by contract on L291 of Test.sol.

**Comment by federicobond** [comment]
Thanks! I just tested a redesigned state machine for the mapCommasToNulls function that solves this problem and is better than the previous code too. I will rebase and push on top of your branch, so commit is still attributed to you.

**Comment by federicobond** [comment]
@maxsam4 just released a new version with the latest changes.

**Pull request closed without merging**
