### PR TITLE
fix: ParameterList member types

### LINKED ISSUE #74: Augment the `Parameter` type
This isn't as much a request, but it's more for me to track (PR will be incoming.)

Basically, the `Parameter` type, as defined [here](https://github.com/federicobond/solidity-parser-antlr/blob/master/index.d.ts#L172-L178) should be more of an alias, as it's really not represented in the AST like this.

For instance, to represent an event declaration node, you would use something like this:

```typescript
const EVENT_NODE = {
  name: "__StatementCoverage",
  parameters: {
    parameters: [
      {
        name: "value",
        type: "VariableDeclaration",
        typeName: { name: "uint32", type: "ElementaryTypeName" },
      },
    ],
    type: "ParameterList",
  },
  type: "EventDefinition",
};
```

If you type `EVENT_NODE` as `EventDefinition`, the type checker will fail because `parameters` can only contain `type: Parameter` children.

### PR DESCRIPTION
**Pull request by andremedeiros**
Fixes #74.

### CODE REVIEW

**Comment by federicobond** [comment]
Sorry to raise this so late, but I am considering just dropping the ParameterList node and having all parameters be VariableDeclaration nodes, what do you think?

**Comment by andremedeiros** [comment]
You'd want to drop the `Parameter` node too, as it's used in the same sort of context as `VariableDeclaration`. I can see that working. It might just [break `prettier-plugin-solidity`](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/master/src/nodes/ParameterList.js) tho, and possibly others, so it's a tough one.

**Comment by federicobond** [comment]
Yes, let's merge this as is and consider the other change later.

**Comment by andremedeiros** [comment]
Any chance you can get another release pushed?

**Comment by federicobond** [comment]
Done. `0.4.5` is published in npm.

**Pull request merged**
