### PR TITLE
Remove ParameterList and Parameter node types

### PR DESCRIPTION
**Pull request by federicobond**

### CODE REVIEW

**Comment by Janther** [comment]
similar to #67, modifiers can be declared without parentheses or with parentheses and no arguments.
Could you return `null` when there are no parentheses, parentheses without arguments `[]`?

**Comment by federicobond** [comment]
Sure. Note that this change moves the parser further away from an AST towards a concrete syntax tree, which is convenient for some use cases, but may get us into trouble later. I may reconsider this decision in the future.

**Comment by Janther** [comment]
You are right. I freaked out because of that particular test not passing.

I don't see any problem with prettier-solidity enforcing the removal of parentheses from the code in this case.

I'm creating a list of valid use cases where prettier-solidity should change the code other than adding and removing whitespace here and there. This looks like one of those cases but will have to talk it first.

**Comment by Janther** [comment]
I just started a discussion in [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/165) to see what other people think about this subject.

**Comment by federicobond** [comment]
Thank you! Note that I am not altogether against supporting use cases that require a CST, and I definitely want to keep supporting prettier-solidity, but I do want to consider how these changes fit together on the whole instead of going around addressing things on an ad-hoc basis with the end result being pulled between users that want to get a clean abstract view and users who want to know more about the code as written.

**Comment by yxliang01** [comment]
Maybe making this library output both CST and AST would be a good idea? As @federicobond suggested, sometimes we want AST and sometimes CST, but we shouldn't have something in between I guess.

**Comment by yxliang01** [comment]
@federicobond Maybe should also have a dedicated `BREAKING.md` for logging the breaking changes and in `README.md` mentioning the versions having breaking changes?

**Pull request merged**
