### PR TITLE
Now shipping an ES5 version of the module.

### PR DESCRIPTION
**Pull request by blargity**
Some build tooling doesn't yet support ES6 syntax. It's going to be another couple of years before everyone's caught up, so this PR uses `babel-cli` to transpile the code back to ES5 using the `babel-preset-env` configuration.

The built files are put into a `dist` directory. I also needed to restructure the repo a bit so that when babel runs the folder structure is preserved. (If you run `babel --out-dir=dist src antlr4 lib` then all of those directories are flattened into one directory and the `index.js` file gets clobbered from at least one of the folders)

This now allows the package to be used from Create React App applications, and probably others. I tried to keep the tooling as simple as possible. This solution came out of my work trying to get to the bottom of #25.

Let me know if you need any more info from me to enable a merge / publish. I used `npm link` to test this with my own site (https://github.com/coinagecrypto/solidifier) and it works fine for me, and I trust babel quite a bit at this stage, but would still be good to do more testing of other use cases before a publish.

### CODE REVIEW

**Comment by federicobond** [comment]
Can you try something like this?

http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/

**Comment by blargity** [comment]
Yup, sure can, I'll do that now.

**Comment by blargity** [comment]
Done! There are lots of different preferences on how to manage this around the community, but I really like that solution better than having the compiled files in the repo.

**Comment by blargity** [comment]
Note, while I could get the build process to work on both Create React App and Gatsby, the production build would not compile solidity code correctly because Uglify's mangle feature breaks the antlr setup somehow.

I could not find a way to fix this on Create React App without ejecting. Once you eject you'll need to apply a webpack config change similar to the below that I did for Gatsby.

To get this package to work in Gatsby, add the following to `gatsby-node.js`:

```
exports.modifyWebpackConfig = ({ config }) => {
	// https://github.com/gatsbyjs/gatsby/issues/2107
	config.merge({
		node: { fs: 'empty' },
	});

	// Disable uglify's mangle feature because the build doesn't work when mangled.
	// Behaviour when mangle is on is that
	// const ast = parser.parse(contents, { tolerant: true, loc: true });
	// runs successfully, but the ast variable has one single object in it
	// so it hasn't parsed fully.
	const { plugins } = config._config;

	for (const plugin of plugins) {
		if (plugin instanceof webpack.optimize.UglifyJsPlugin) {
			plugin.options.mangle = false;
		}
	}

	return config;
};
```

Congratulations, you're now running production, minified builds of this module in the browser that work.

**Pull request merged**
